Repository game-community-project/front-end, pull requests merged in 2024-01, with the labels that each got.

#7 feat: user mypage, profile modify 기능 추가 중.
  src/App.tsx
  src/dto/UserDto.ts
  src/layout/TopNav.tsx
  src/pages/Login.tsx
  src/pages/user/MyPage.tsx
  src/pages/user/ProfileModify.tsx
Labels: enhancement

#10 feat: 프로필 수정 기능 구현 완료.
  src/layout/TopNav.tsx
  src/pages/user/ProfileModify.tsx
Labels: enhancement

#11 fix: routes file 오류 수정.
  src/Routes.tsx
Labels: bug

#12 Feature/post
  src/App.tsx
  src/layout/TopNav.tsx
  src/pages/Login.tsx
  src/pages/News.tsx
  src/pages/Signup.tsx
  src/pages/board/Board.css
  src/pages/board/Board.tsx
  src/pages/board/CreatePost.tsx
  src/pages/board/Post.css
  src/pages/board/Post.tsx
  src/pages/board/UpdatePost.tsx
  src/pages/user/MyPage.tsx
Labels: enhancement

#13 feat: team 기능 추가.
  src/dto/Team.ts
  src/pages/board/Board.tsx
  src/pages/team/Team.css
  src/pages/team/Team.tsx
  yarn.lock
Labels: enhancement

#16 Feature/post
  src/App.tsx
  src/layout/Footer.css
  src/layout/Footer.tsx
  src/layout/Header.css
  src/layout/TopNav.css
  src/layout/TopNav.tsx
  src/pages/Logout.tsx
  src/pages/board/Board.tsx
Labels: enhancement

#17 feat: admin page에서 유저 조회 기능 추가.
  src/dto/UserDto.ts
  src/pages/admin/Admin.tsx
  src/pages/user/ProfileModify.tsx
  yarn.lock
Labels: enhancement

#18 Feature/post
  .gitignore
  package-lock.json
  package.json
  src/pages/board/CreatePost.tsx
  src/pages/board/Post.css
  src/pages/board/Post.tsx
  src/pages/board/UpdatePost.tsx
  src/react-s3.d.ts
  yarn.lock
Labels: enhancement

#20 feat: 카카오 로그인 기능 구현
  src/App.tsx
  src/pages/Login.tsx
  src/pages/OAuth.tsx
Labels: enhancement

#19 feat: user list에서 유저 클릭하면 user info 볼 수 있도록 수정.
  package-lock.json
  package.json
  src/App.tsx
  src/layout/TopNav.tsx
  src/pages/admin/UserInfo.tsx
  src/pages/admin/UserList.tsx
  yarn.lock
Labels: enhancement

#21 fix: login시 화면 갱신
  src/pages/Login.tsx
Labels: bug

#23 Feature/new comment
  src/pages/board/Post.css
  src/pages/board/Post.tsx
Labels: enhancement

#25 Feature/team
  src/App.tsx
  src/pages/team/AddUserToTeam.tsx
  src/pages/team/CreateTeam.tsx
  src/pages/team/DeleteUserFromTeam.tsx
  src/pages/team/Team.css
  src/pages/team/Team.tsx
  src/pages/team/TeamPage.tsx
  src/pages/team/UpdateTeam.tsx
Labels: enhancement

#29 feat: dropdown 경로 수정.
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/layout/TopNav.tsx
  src/pages/user/MyPage.tsx
  src/pages/user/ProfileModify.tsx
  yarn.lock
Labels: bug

#30 feat: localhost 경로 수정
  src/pages/user/ProfileModify.tsx
Labels: bug

#32 feat: back end 주소 수정.
  src/pages/Login.tsx
  src/pages/Logout.tsx
  src/pages/Signup.tsx
  src/pages/admin/UserInfo.tsx
  src/pages/admin/UserList.tsx
  src/pages/board/Board.tsx
  src/pages/board/CreatePost.tsx
  src/pages/board/Post.tsx
  src/pages/board/UpdatePost.tsx
  src/pages/guestbook/Guestbook.tsx
  src/pages/team/AddUserToTeam.tsx
  src/pages/team/CreateTeam.tsx
  src/pages/team/DeleteUserFromTeam.tsx
  src/pages/team/Team.tsx
  src/pages/team/TeamPage.tsx
  src/pages/team/UpdateTeam.tsx
  src/pages/user/MyPage.tsx
  src/pages/user/ProfileModify.tsx
Labels: bug, enhancement

#33 Feature/address modify
  public/index.html
  public/spartagameclub.ico
  public/spartagameclub.png
  src/pages/Home.tsx
  src/pages/OAuth.tsx
Labels: bug

#34 Feature/post close
  .vscode/launch.json
  src/dto/Board.ts
  src/dto/Post.ts
  src/pages/board/Board.css
  src/pages/board/Board.tsx
  src/pages/board/Post.css
  src/pages/board/Post.tsx
Labels: enhancement

#35 feat: gameName삭제 및 팀 탈퇴 추가
  src/pages/board/Board.tsx
  src/pages/team/AddUserToTeam.tsx
  src/pages/team/CreateTeam.tsx
  src/pages/team/Team.tsx
  src/pages/team/UpdateTeam.tsx
  yarn.lock
Labels: enhancement
